spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/start_the_count
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    time-zone: America/Sao_Paulo
    locale: pt_BR
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
springdoc:
  swagger-ui:
    operations-sorter: method
